### ISSUE TITLE
Eval code not runnable

### ISSUE THREAD

**Issue by msaroufim** [jiofidelus/TSOTSALLM#1]
can you push a quick fix for this?  https://github.com/jiofidelus/TSOTSALLM/blob/main/Tsotsallm/llama_recipes/main.py

model = load_peft_model(token=os.environ['HUGGINGFACE_REPO'])

token is not a valid parameter and just passing in llama2 doesnt work either

**Comment by jeanpetitt** [comment]
Hi Mark
The issues is already fixed
thank you
